import type { Node, Edge } from '@xyflow/react'
import type { ComponentNodeData, BOMEntry } from '../types'
import { COMPONENT_LIBRARY } from '../data/components'

function getComponentsOnCanvas(nodes: Node[]): BOMEntry[] {
  const counts = new Map<string, number>()

  nodes.forEach(n => {
    const data = n.data as ComponentNodeData
    if (!data.typeId) return
    counts.set(data.typeId, (counts.get(data.typeId) ?? 0) + 1)
  })

  const bomEntries: BOMEntry[] = []
  let refCounter: Record<string, number> = {}

  counts.forEach((qty, typeId) => {
    const def = COMPONENT_LIBRARY.find(c => c.typeId === typeId)
    if (!def) return

    const prefix =
      def.category === 'MCU' ? 'U' :
      def.category === 'Sensor' ? 'U' :
      def.category === 'Power' ? 'BAT' :
      def.category === 'Passive' ? (def.typeId.startsWith('cap') ? 'C' : 'R') : 'U'

    refCounter[prefix] = (refCounter[prefix] ?? 0) + 1
    const refBase = `${prefix}${refCounter[prefix]}`

    // Supplier mapping
    const supplierMap: Record<string, { supplier: string; pn: string }> = {
      'xiao_ble_nrf52840': { supplier: 'Seeed Studio', pn: '102010448' },
      'max30102':          { supplier: 'SparkFun / DFRobot', pn: 'SEN-16474' },
      'mpu6050':           { supplier: 'Adafruit / DFRobot', pn: '3886' },
      'tmp117':            { supplier: 'SparkFun', pn: 'SEN-15805' },
      'ens160_aht21':      { supplier: 'DFRobot', pn: 'SEN0515' },
      'ltr390':            { supplier: 'Adafruit', pn: '4831' },
      'lipo_battery':      { supplier: 'Seeed Studio / Generic', pn: '317080012' },
      'resistor_4k7':      { supplier: 'Generic', pn: 'RC0402FR-074K7L' },
      'resistor_10k':      { supplier: 'Generic', pn: 'RC0402FR-0710KL' },
      'cap_100nf':         { supplier: 'Generic', pn: 'GRM155R61A104KA01D' },
      'cap_10uf':          { supplier: 'Generic', pn: 'GRM31CR61A106KA01L' },
    }

    const sup = supplierMap[typeId] ?? { supplier: 'Unknown', pn: '' }

    const i2cNotes = def.i2cAddresses.length > 0
      ? `I2C: ${def.i2cAddresses.map(a => a.hex).join('/')}`
      : ''

    const packageMap: Record<string, string> = {
      'xiao_ble_nrf52840': 'Custom SMD Module',
      'max30102':          'Breakout Board',
      'mpu6050':           'Breakout Board',
      'tmp117':            'Breakout Board',
      'ens160_aht21':      'Breakout Board',
      'ltr390':            'Breakout Board',
      'lipo_battery':      'JST-PH 2.0mm',
      'resistor_4k7':      '0402',
      'resistor_10k':      '0402',
      'cap_100nf':         '0402',
      'cap_10uf':          '0805',
    }

    bomEntries.push({
      reference: refBase,
      value: def.shortLabel,
      description: def.description.split('.')[0],
      package: packageMap[typeId] ?? 'Through-Hole',
      quantity: qty,
      supplier: sup.supplier,
      partNumber: sup.pn,
      notes: [i2cNotes, `${def.voltageRating}V`].filter(Boolean).join(' | '),
    })
  })

  return bomEntries
}

export function generateCSVBOM(nodes: Node[], edges: Edge[]): string {
  const _ = edges.length
  const bom = getComponentsOnCanvas(nodes)

  const header = ['Reference', 'Value', 'Description', 'Package', 'Quantity', 'Supplier', 'Part Number', 'Notes']
  const rows = bom.map(entry => [
    entry.reference,
    entry.value,
    `"${entry.description}"`,
    entry.package,
    entry.quantity.toString(),
    entry.supplier,
    entry.partNumber,
    `"${entry.notes}"`,
  ])

  return [header.join(','), ...rows.map(r => r.join(','))].join('\n')
}

export function generateNetlist(nodes: Node[], edges: Edge[]): string {
  const lines: string[] = [
    '# EasyEDA-Compatible Netlist (CSV format)',
    '# Generated by IoT Schematic Canvas',
    `# Date: ${new Date().toISOString()}`,
    '#',
    '# Format: NetName, Component.Pin, Component.Pin, ...',
    '',
    'NetName,Connections',
  ]

  // Group edges by signal / net
  const nets = new Map<string, string[]>()

  edges.forEach(edge => {
    const srcNode = nodes.find(n => n.id === edge.source)
    const tgtNode = nodes.find(n => n.id === edge.target)
    if (!srcNode || !tgtNode) return

    const srcData = srcNode.data as ComponentNodeData
    const tgtData = tgtNode.data as ComponentNodeData

    const srcLabel = srcData.instanceId ?? srcNode.id
    const tgtLabel = tgtData.instanceId ?? tgtNode.id

    const srcPinId = edge.sourceHandle?.split('__')[1] ?? 'P'
    const tgtPinId = edge.targetHandle?.split('__')[1] ?? 'P'

    const netKey = edge.label?.toString() ?? `Net_${edge.id.slice(0, 6)}`
    const srcPin = `${srcLabel}.${srcPinId}`
    const tgtPin = `${tgtLabel}.${tgtPinId}`

    const existing = nets.get(netKey) ?? []
    if (!existing.includes(srcPin)) existing.push(srcPin)
    if (!existing.includes(tgtPin)) existing.push(tgtPin)
    nets.set(netKey, existing)
  })

  nets.forEach((pins, netName) => {
    lines.push(`${netName},${pins.join(',')}`)
  })

  return lines.join('\n')
}

export function downloadBOM(nodes: Node[], edges: Edge[]): void {
  const content = generateCSVBOM(nodes, edges)
  const blob = new Blob([content], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'iot_wearable_bom.csv'
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadNetlist(nodes: Node[], edges: Edge[]): void {
  const content = generateNetlist(nodes, edges)
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'iot_wearable_netlist.csv'
  a.click()
  URL.revokeObjectURL(url)
}
